import { Conditions, DoubleDownOnEnum, PayRatioEnum } from "../models";

export const defaultConditions: Conditions = {
  title: "Default Conditions",
  S17: false,
  RSA:  true,
  MHFS: 4,
  DSA: true,
  RD: true,
  RRD: true,
  DS21: true,
  DFL: true,
  RDFL: false,
  DAS: true,
  MSE: true,
  LCD: false,
  reshuffleOnDealerChange: false,
  burnCardOnDealerChange: true,
  payRatio: PayRatioEnum.THREE_to_TWO,
  payRatioFromAA: PayRatioEnum.ONE_to_ONE,
  canSurrenderAfterSplit: false,
  canRescueAfterSplit: true,
  LS: true,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 75,
  countBurnCard: false,
  handsPerDealer: 500,
  DD: DoubleDownOnEnum.DA2,
}

export const deviationConditions: Conditions = {
  title: "Deviation Conditions",
  S17: false,
  RSA:  true,
  MHFS: 4,
  DSA: true,
  RD: true,
  RRD: true,
  DS21: true,
  DFL: true,
  RDFL: false,
  DAS: true,
  MSE: true,
  LCD: false,
  reshuffleOnDealerChange: false,
  burnCardOnDealerChange: false,
  payRatio: PayRatioEnum.THREE_to_TWO,
  payRatioFromAA: PayRatioEnum.ONE_to_ONE,
  canSurrenderAfterSplit: false,
  canRescueAfterSplit: true,
  LS: true,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 0,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 90,
  countBurnCard: false,
  handsPerDealer: 100000,
  DD: DoubleDownOnEnum.DA2,
}

export const conditionTitles: string[] = ["Default Conditions"];

export const allDefaultConditions: { [k: string]: Conditions } = {
  "Default Conditions": defaultConditions,
  "Deviation Conditions": deviationConditions,
};